export const templateRegistry = [

/* MODERN */

{ id:"modern-default", name:"Modern Default", category:"modern", popular:true },
{ id:"modern-pro", name:"Modern Pro", category:"modern", popular:true },
{ id:"modern-slate", name:"Modern Slate", category:"modern", popular:true },
{ id:"modern-edge", name:"Modern Edge", category:"modern", newest:true },
{ id:"modern-clean", name:"Modern Clean", category:"modern", newest:true },
{ id:"modern-grid", name:"Modern Grid", category:"modern" },
{ id:"modern-folio", name:"Modern Folio", category:"modern" },
{ id:"modern-frame", name:"Modern Frame", category:"modern", popular:true },
{ id:"modern-glass", name:"Modern Glass", category:"modern" },
{ id:"modern-neon", name:"Modern Neon", category:"modern", newest:true },
{ id:"modern-stripe", name:"Modern Stripe", category:"modern" },
{ id:"modern-cobalt", name:"Modern Cobalt", category:"modern", popular:true },
{ id:"modern-zenith", name:"Modern Zenith", category:"modern" },
{ id:"modern-studio", name:"Modern Studio", category:"modern" },
{ id:"modern-fusion", name:"Modern Fusion", category:"modern", newest:true },
{ id:"modern-orbit", name:"Modern Orbit", category:"modern" },
{ id:"modern-crest", name:"Modern Crest", category:"modern", popular:true },
{ id:"modern-ribbon", name:"Modern Ribbon", category:"modern" },
{ id:"modern-dock", name:"Modern Dock", category:"modern" },
{ id:"modern-prime", name:"Modern Prime", category:"modern", newest:true },
{ id:"modern-aurora", name:"Modern Aurora", category:"modern", newest:true },
{ id:"modern-luxe", name:"Modern Luxe", category:"modern", newest:true },
{ id:"modern-bento", name:"Modern Bento", category:"modern", newest:true },
{ id:"modern-eclipse", name:"Modern Eclipse", category:"modern", newest:true },
{ id:"modern-mosaic", name:"Modern Mosaic", category:"modern", newest:true },
{ id:"modern-horizon", name:"Modern Horizon", category:"modern", newest:true },
{ id:"modern-vertex", name:"Modern Vertex", category:"modern", newest:true },
{ id:"modern-capsule", name:"Modern Capsule", category:"modern", newest:true },
{ id:"modern-lens", name:"Modern Lens", category:"modern", newest:true },
{ id:"modern-flare", name:"Modern Flare", category:"modern", newest:true },
{ id:"modern-pulse", name:"Modern Pulse", category:"modern", newest:true },
{ id:"modern-ember", name:"Modern Ember", category:"modern", newest:true },
{ id:"modern-orchid", name:"Modern Orchid", category:"modern", newest:true },
{ id:"modern-coast", name:"Modern Coast", category:"modern", newest:true },
{ id:"modern-onyx", name:"Modern Onyx", category:"modern", newest:true },
{ id:"modern-atelier", name:"Modern Atelier", category:"modern", newest:true },

/* MINIMAL */

{ id:"minimal-light", name:"Minimal Light", category:"minimal", popular:true },
{ id:"minimal-dark", name:"Minimal Dark", category:"minimal", newest:true },
{ id:"minimal-white", name:"Minimal White", category:"minimal", popular:true },
{ id:"minimal-soft", name:"Minimal Soft", category:"minimal", newest:true },
{ id:"minimal-pro", name:"Minimal Pro", category:"minimal", popular:true },
{ id:"minimal-mono", name:"Minimal Mono", category:"minimal" },
{ id:"minimal-calm", name:"Minimal Calm", category:"minimal" },
{ id:"minimal-linen", name:"Minimal Linen", category:"minimal" },
{ id:"minimal-air", name:"Minimal Air", category:"minimal", newest:true },
{ id:"minimal-paper", name:"Minimal Paper", category:"minimal" },
{ id:"minimal-stone", name:"Minimal Stone", category:"minimal" },
{ id:"minimal-bare", name:"Minimal Bare", category:"minimal" },
{ id:"minimal-muse", name:"Minimal Muse", category:"minimal", popular:true },
{ id:"minimal-slate", name:"Minimal Slate", category:"minimal" },
{ id:"minimal-civic", name:"Minimal Civic", category:"minimal" },
{ id:"minimal-outline", name:"Minimal Outline", category:"minimal" },
{ id:"minimal-hush", name:"Minimal Hush", category:"minimal" },
{ id:"minimal-ink", name:"Minimal Ink", category:"minimal", popular:true },
{ id:"minimal-fold", name:"Minimal Fold", category:"minimal" },
{ id:"minimal-nord", name:"Minimal Nord", category:"minimal", newest:true },
{ id:"minimal-gridline", name:"Minimal Gridline", category:"minimal", newest:true },
{ id:"minimal-borderless", name:"Minimal Borderless", category:"minimal", newest:true },
{ id:"minimal-compact", name:"Minimal Compact", category:"minimal", newest:true },
{ id:"minimal-matrix", name:"Minimal Matrix", category:"minimal", newest:true },
{ id:"minimal-arc", name:"Minimal Arc", category:"minimal", newest:true },
{ id:"minimal-signal", name:"Minimal Signal", category:"minimal", newest:true },
{ id:"minimal-zen", name:"Minimal Zen", category:"minimal", newest:true },
{ id:"minimal-inkline", name:"Minimal Inkline", category:"minimal", newest:true },
{ id:"minimal-studio", name:"Minimal Studio", category:"minimal", newest:true },
{ id:"minimal-lattice", name:"Minimal Lattice", category:"minimal", newest:true },
{ id:"minimal-copper", name:"Minimal Copper", category:"minimal", newest:true },
{ id:"minimal-wave", name:"Minimal Wave", category:"minimal", newest:true },
{ id:"minimal-summit", name:"Minimal Summit", category:"minimal", newest:true },

/* CLASSIC */

{ id:"classic-default", name:"Classic Default", category:"classic", popular:true },
{ id:"classic-gst", name:"Classic GST", category:"classic", popular:true },
{ id:"classic-bold", name:"Classic Bold", category:"classic", newest:true },
{ id:"classic-ledger", name:"Classic Ledger", category:"classic", popular:true },
{ id:"classic-office", name:"Classic Office", category:"classic", newest:true },
{ id:"classic-india", name:"Classic India", category:"classic", popular:true },
{ id:"classic-serif", name:"Classic Serif", category:"classic" },
{ id:"classic-heritage", name:"Classic Heritage", category:"classic" },
{ id:"classic-ivory", name:"Classic Ivory", category:"classic" },
{ id:"classic-border", name:"Classic Border", category:"classic", popular:true },
{ id:"classic-registrar", name:"Classic Registrar", category:"classic" },
{ id:"classic-formal", name:"Classic Formal", category:"classic" },
{ id:"classic-trader", name:"Classic Trader", category:"classic" },
{ id:"classic-stamp", name:"Classic Stamp", category:"classic", newest:true },
{ id:"classic-colonial", name:"Classic Colonial", category:"classic" },
{ id:"classic-notary", name:"Classic Notary", category:"classic" },
{ id:"classic-merchant", name:"Classic Merchant", category:"classic", popular:true },
{ id:"classic-charter", name:"Classic Charter", category:"classic" },
{ id:"classic-vintage", name:"Classic Vintage", category:"classic" },
{ id:"classic-royal", name:"Classic Royal", category:"classic", newest:true }
,
{ id:"classic-parchment", name:"Classic Parchment", category:"classic", newest:true },
{ id:"classic-courier", name:"Classic Courier", category:"classic", newest:true },
{ id:"classic-deed", name:"Classic Deed", category:"classic", newest:true },
{ id:"classic-stationery", name:"Classic Stationery", category:"classic", newest:true },
{ id:"classic-copperplate", name:"Classic Copperplate", category:"classic", newest:true },
{ id:"classic-saffron", name:"Classic Saffron", category:"classic", newest:true },
{ id:"classic-carbon", name:"Classic Carbon", category:"classic", newest:true },
{ id:"classic-archive", name:"Classic Archive", category:"classic", newest:true },
{ id:"classic-marble", name:"Classic Marble", category:"classic", newest:true },
{ id:"classic-sealblue", name:"Classic Seal Blue", category:"classic", newest:true },
{ id:"classic-press", name:"Classic Press", category:"classic", newest:true },
{ id:"classic-crown", name:"Classic Crown", category:"classic", newest:true },
{ id:"classic-vellum", name:"Classic Vellum", category:"classic", newest:true }

]
