// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(app)/dashboard/business/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/business">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/business/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/customers/[phone]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/customers/[phone]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/customers/[phone]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/customers">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/invoices/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/invoices/create">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/invoices/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/invoices/edit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/invoices/edit/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/invoices/edit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/invoices">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/invoices/view/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/invoices/view/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/invoices/view/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/products">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/settings/invoice-visibility/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/invoice-visibility">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/settings/invoice-visibility/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/settings/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/report">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/settings/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/templates/classic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/templates/classic">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/templates/classic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/templates/minimal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/templates/minimal">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/templates/minimal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/templates/modern/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/templates/modern">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/templates/modern/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/templates">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/upgrade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/upgrade">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/upgrade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/billing-software-for-small-business/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing-software-for-small-business">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/billing-software-for-small-business/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/create-invoice-online/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create-invoice-online">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/create-invoice-online/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/download-invoice-pdf/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/download-invoice-pdf">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/download-invoice-pdf/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/free-invoice-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/free-invoice-generator">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/free-invoice-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/gst-invoice-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gst-invoice-generator">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/gst-invoice-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/invoice-customization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice-customization">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/invoice-customization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/invoice-generator-india/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice-generator-india">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/invoice-generator-india/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/invoice-templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice-templates">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/invoice-templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/invoice-pdf/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice-pdf">> = Specific
  const handler = {} as typeof import("../../../app/invoice-pdf/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/setup/profile/bank/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup/profile/bank">> = Specific
  const handler = {} as typeof import("../../../app/setup/profile/bank/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/setup/profile/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup/profile/contact">> = Specific
  const handler = {} as typeof import("../../../app/setup/profile/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/setup/profile/finalizing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup/profile/finalizing">> = Specific
  const handler = {} as typeof import("../../../app/setup/profile/finalizing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/setup/profile/logo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup/profile/logo">> = Specific
  const handler = {} as typeof import("../../../app/setup/profile/logo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/setup/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup/profile">> = Specific
  const handler = {} as typeof import("../../../app/setup/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/setup/profile/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup/profile/settings">> = Specific
  const handler = {} as typeof import("../../../app/setup/profile/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/setup/profile/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup/profile/terms">> = Specific
  const handler = {} as typeof import("../../../app/setup/profile/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/account/email-change-policy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/email-change-policy">> = Specific
  const handler = {} as typeof import("../../../app/api/account/email-change-policy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/purge-invoice-pdfs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/purge-invoice-pdfs">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/purge-invoice-pdfs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/invoice-pdf-export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoice-pdf-export">> = Specific
  const handler = {} as typeof import("../../../app/api/invoice-pdf-export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/invoice-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoice-pdf">> = Specific
  const handler = {} as typeof import("../../../app/api/invoice-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(app)/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(marketing)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(marketing)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
