// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/billing-software-for-small-business" | "/create-invoice-online" | "/dashboard" | "/dashboard/business" | "/dashboard/customers" | "/dashboard/customers/[phone]" | "/dashboard/invoices" | "/dashboard/invoices/create" | "/dashboard/invoices/edit/[id]" | "/dashboard/invoices/view/[id]" | "/dashboard/products" | "/dashboard/settings" | "/dashboard/settings/invoice-visibility" | "/dashboard/settings/report" | "/dashboard/templates" | "/dashboard/templates/classic" | "/dashboard/templates/minimal" | "/dashboard/templates/modern" | "/dashboard/upgrade" | "/download-invoice-pdf" | "/features" | "/free-invoice-generator" | "/gst-invoice-generator" | "/invoice-customization" | "/invoice-generator-india" | "/invoice-pdf" | "/invoice-templates" | "/pricing" | "/setup/profile" | "/setup/profile/bank" | "/setup/profile/contact" | "/setup/profile/finalizing" | "/setup/profile/logo" | "/setup/profile/settings" | "/setup/profile/terms" | "/terms"
type AppRouteHandlerRoutes = "/api/account/email-change-policy" | "/api/cron/purge-invoice-pdfs" | "/api/cron/purge-logo-orphans" | "/api/invoice-pdf" | "/api/invoice-pdf-export" | "/api/metadata-card" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/account/email-change-policy": {}
  "/api/cron/purge-invoice-pdfs": {}
  "/api/cron/purge-logo-orphans": {}
  "/api/invoice-pdf": {}
  "/api/invoice-pdf-export": {}
  "/api/metadata-card": {}
  "/auth/callback": {}
  "/billing-software-for-small-business": {}
  "/create-invoice-online": {}
  "/dashboard": {}
  "/dashboard/business": {}
  "/dashboard/customers": {}
  "/dashboard/customers/[phone]": { "phone": string; }
  "/dashboard/invoices": {}
  "/dashboard/invoices/create": {}
  "/dashboard/invoices/edit/[id]": { "id": string; }
  "/dashboard/invoices/view/[id]": { "id": string; }
  "/dashboard/products": {}
  "/dashboard/settings": {}
  "/dashboard/settings/invoice-visibility": {}
  "/dashboard/settings/report": {}
  "/dashboard/templates": {}
  "/dashboard/templates/classic": {}
  "/dashboard/templates/minimal": {}
  "/dashboard/templates/modern": {}
  "/dashboard/upgrade": {}
  "/download-invoice-pdf": {}
  "/features": {}
  "/free-invoice-generator": {}
  "/gst-invoice-generator": {}
  "/invoice-customization": {}
  "/invoice-generator-india": {}
  "/invoice-pdf": {}
  "/invoice-templates": {}
  "/pricing": {}
  "/setup/profile": {}
  "/setup/profile/bank": {}
  "/setup/profile/contact": {}
  "/setup/profile/finalizing": {}
  "/setup/profile/logo": {}
  "/setup/profile/settings": {}
  "/setup/profile/terms": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
